name: buzzup
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.3.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.11
  formz: ^0.8.0
  riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  flutter_platform_widgets: ^7.0.1
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  graphql_flutter: ^5.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  rxdart: ^0.28.0
  google_fonts: ^6.2.1
  animated_list_plus: ^0.5.2
  rive_animated_icon: ^2.0.1
  path_provider: ^2.1.5
  animations: ^2.0.11
  collection: ^1.18.0
  sign_in_button: ^3.2.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  flutter_gen_runner: ^5.8.0
  mockito: ^5.4.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Josefin
  #     fonts:
  #       - asset: assets/fonts/JosefinSans-Regular.ttf
  #   - family: Yeseva
  #     fonts:
  #       - asset: assets/fonts/YesevaOne-Regular.ttf

flutter_gen:
  output: lib/core/common/gen/
  line_length: 80
